### ISSUE TITLE
replace segmentation evaluation code from waterz to gala

### ISSUE THREAD

**Issue by jingpengw** [seung-lab/chunkflow#154]
gala is easier to install and have more complete metrics, including Rand Index, Adjusted Rand Index, Flowlkes-Mallows index, and Variation of Information.

https://github.com/janelia-flyem/gala/blob/master/gala/evaluate.py

**Comment by jingpengw** [comment]
or rewrite the code in reneu package.

**Comment by geekswaroop** [comment]
Hi, @jingpengw do you think a complete porting of segmentation evaluation from waterz to gala is required?

**Comment by jingpengw** [comment]
@geekswaroop Currently, no one require this transition, and gala seems not maintained. What do you think? do you need it?

**Comment by geekswaroop** [comment]
Although gala has not been maintained in recent times, we can make use of the complete metrics as you mentioned.. We can probably give users the choice of the evaluation method they need.

**Comment by geekswaroop** [comment]
I had been pondering on how to implement the gala function. Installing gala as a pip package followed by usage of the evaluation chosen by the user seemed like a straightforward way. Is there any other way you would recommend? 
( I am referring to [this](https://gala.readthedocs.io/en/latest/api/gala.evaluate.html) doc of gala for the usage of it's API)

**Comment by jingpengw** [comment]
thank you for all the help. I have integrated it by simply copying the code. I also used the function from scipy.
