### ISSUE TITLE
命令错误

### ISSUE THREAD

**Issue by genggeng-123** [seung-lab/chunkflow#252]
![Uploading 截屏2021-08-13 上午9.22.01.png…]()

**Comment by jingpengw** [comment]
才注意到你们提交了issue，看不到你的图片。

**Comment by genggeng-123** [comment]
<img width="793" alt="截屏2021-08-31 下午5 22 03" src="https://user-images.githubusercontent.com/83057527/131477580-6815959e-6d78-40c3-ae00-55943a468d52.png">

**Comment by jingpengw** [comment]
我刚刚release了新的版本：
https://pypi.org/project/chunkflow/

你试试
```
pip install -U chunkflow
```

**Comment by jingpengw** [comment]
我自己测试过，我这里是可以运行那个命令的，没有问题。

**Comment by genggeng-123** [comment]
感谢老师的帮助，现在运行这条语句没有报错啦。


| |
耿艺
|
|
***@***.***
|
签名由网易邮箱大师定制


在2021年08月31日 18:30，Jingpeng ***@***.***> 写道：

我自己测试过，我这里是可以运行那个命令的，没有问题。

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
