### ISSUE TITLE
chunkflow has been installed,but an error occurs when running this instruction.

### ISSUE THREAD

**Issue by Crystalqijing** [seung-lab/chunkflow#253]
![2](https://user-images.githubusercontent.com/83045487/129298758-0d7e319e-08c0-420e-b2b5-ce6133634ab1.png)
![1](https://user-images.githubusercontent.com/83045487/129298761-92c02c2d-69c6-466c-adff-7b3201f60b03.png)
![3](https://user-images.githubusercontent.com/83045487/129298764-f4565808-1f64-4f29-bfb3-ac9a51d7df3e.png)

**Comment by jingpengw** [comment]
it seems that it was installed successfully.
could you paste your code of `neuroglancer.py`?

**Comment by Crystalqijing** [comment]
![neuroglancer](https://user-images.githubusercontent.com/83045487/131465513-fffaba84-3a5b-46f7-bd1a-cf12fdbbcbd3.jpg)

**Comment by jingpengw** [comment]
I just updated the code release. Please update your code using `pip install -U chunkflow` and try it again.

**Comment by Crystalqijing** [comment]
There is no problem with the chunkflow installation, and the instructions can also run normally, but after the instructions are executed, there is a URL that cannot be accessed for unknown reasons.
![chunkflow1](https://user-images.githubusercontent.com/83045487/131593118-49253f5a-2744-4b90-b15d-fd0028b5d810.png)
![chuankflow2](https://user-images.githubusercontent.com/83045487/131593151-483a78fc-d19b-4261-9133-78402e098d94.png)

**Comment by jingpengw** [comment]
you can replace the computer host name `laptop...` to `localhost`

**Comment by jingpengw** [comment]
does it work?

**Comment by Crystalqijing** [comment]
yes,It's ok.Thank you!
