### ISSUE TITLE
input-patch-size etc in setup_env

### ISSUE THREAD

**Issue by ranlu** [seung-lab/chunkflow#273]
Just a question. According to [this line](https://github.com/seung-lab/chunkflow/blob/master/chunkflow/flow/setup_env.py#L77), it seems parameters like input_patch_size should be converted to mip0 numbers so they can be added to volume_start directly. So during setup_env, for a mip1 net with input patch size (256,256,20) I should use (512,512,20), but during inference I should use (256,256,20). Is this the right approach?

**Comment by jingpengw** [comment]
sorry for the late reply. Somehow, I did not receive email notifications for issues!

I think you are right, but I am not completely sure!

**Comment by jingpengw** [comment]
I just learned that I have to set up the watch for all activities.

**Comment by jingpengw** [comment]
you can set the `mip=1` parameter.
