### ISSUE TITLE
[Operator] kimimaro skeletonization

### ISSUE THREAD

**Issue by jingpengw** [seung-lab/chunkflow#90]
https://github.com/seung-lab/kimimaro

**Comment by jingpengw** [comment]
https://github.com/seung-lab/chunkflow/pull/179

**Comment by william-silversmith** [comment]
Hi Jingpeng, I was reviewing other implementations for the igneous paper and I think this is missing 1vx overlap to enable trivial joining. Kimimaro post-processing might work decently well without it (it'll join edges closer than the nearest boundary) but I never checked to see how well that works on its own. If you tested this on a large scale and it worked fine, that would also be great to know!

**Comment by jingpengw** [comment]
I have never really completed dense skeletonization. I will try it out a few months later.

**Comment by jingpengw** [comment]
this feature is more appropriate to be made as a plugin rather than an operator.
